"""awards model and manage_awards permission

Revision ID: 0045e4df859c
Revises: bd58d7a4eb3f
Create Date: 2025-07-06 11:03:46.956211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from database import Base
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0045e4df859c'
down_revision: Union[str, None] = 'bd58d7a4eb3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('awards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('recipient', sa.String(), nullable=False),
    sa.Column('recipient_type', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('organization', sa.String(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('categories', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('publications', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_awards_id'), 'awards', ['id'], unique=False)
    # Add MANAGE_AWARDS permission and assign to OFFICER (role_id=4)
    from sqlalchemy.sql import table, column
    permissions_table = table('permissions',
        column('id', sa.Integer),
        column('name', sa.String),
        column('category', sa.String)
    )
    op.bulk_insert(permissions_table, [
        {'id': 13, 'name': 'MANAGE_AWARDS', 'category': 'POST'}
    ])
    role_permissions_table = table('roles_permissions',
        column('id', sa.Integer),
        column('role_id', sa.Integer),
        column('permission_id', sa.Integer)
    )
    op.bulk_insert(role_permissions_table, [
        {'id': 101, 'role_id': 4, 'permission_id': 13}
    ])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_awards_id'), table_name='awards')
    op.drop_table('awards')
    # ### end Alembic commands ###
