"""update equipment booking and categories structure for int ids and officer management

Revision ID: 20213ceff01a
Revises: 753ffdf6d462
Create Date: 2025-07-06 12:58:58.777291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from database import Base


# revision identifiers, used by Alembic.
revision: str = '20213ceff01a'
down_revision: Union[str, None] = '753ffdf6d462'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Drop foreign key constraints before altering column types
    op.drop_constraint('equipment_bookings_equipment_id_fkey', 'equipment_bookings', type_='foreignkey')
    op.drop_constraint('equipment_category_id_fkey', 'equipment', type_='foreignkey')

    # Now alter the columns
    op.alter_column('equipment', 'id',
                    existing_type=sa.VARCHAR(),
                    type_=sa.Integer(),
                    existing_nullable=False,
                    postgresql_using='id::integer',
                    autoincrement=True)
    op.alter_column('equipment', 'category_id',
                    existing_type=sa.VARCHAR(),
                    type_=sa.Integer(),
                    existing_nullable=False,
                    postgresql_using='category_id::integer')
    op.alter_column('equipment_bookings', 'id',
                    existing_type=sa.VARCHAR(),
                    type_=sa.Integer(),
                    existing_nullable=False,
                    postgresql_using='id::integer',
                    autoincrement=True)
    op.alter_column('equipment_bookings', 'equipment_id',
                    existing_type=sa.VARCHAR(),
                    type_=sa.Integer(),
                    existing_nullable=False,
                    postgresql_using='equipment_id::integer')
    op.alter_column('equipment_categories', 'id',
                    existing_type=sa.VARCHAR(),
                    type_=sa.Integer(),
                    existing_nullable=False,
                    postgresql_using='id::integer',
                    autoincrement=True)

    # Re-create the foreign key constraints
    op.create_foreign_key('equipment_category_id_fkey', 'equipment', 'equipment_categories', ['category_id'], ['id'])
    op.create_foreign_key('equipment_bookings_equipment_id_fkey', 'equipment_bookings', 'equipment', ['equipment_id'], ['id'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('equipment_categories', 'id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('equipment_bookings', 'equipment_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('equipment_bookings', 'id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('equipment', 'category_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('equipment', 'id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
