"""add_faculty_table

Revision ID: 3f51ed896918
Revises: 5ac45949126a
Create Date: 2025-07-06 17:31:03.021657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from database import Base
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f51ed896918'
down_revision: Union[str, None] = '5ac45949126a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('designation', sa.Enum('PROFESSOR', 'ASSOCIATE_PROFESSOR', 'ASSISTANT_PROFESSOR', 'LECTURER', name='facultydesignation'), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('expertise', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('office', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('publications', sa.Integer(), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.Column('is_chairman', sa.Boolean(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('education', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('courses', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('research_interests', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_faculty_id'), 'faculty', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_faculty_id'), table_name='faculty')
    op.drop_table('faculty')
    # ### end Alembic commands ###
