"""update_faculty_model

Revision ID: 96c75a9eb45f
Revises: 3f51ed896918
Create Date: 2025-07-06 17:34:00.463949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from database import Base
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96c75a9eb45f'
down_revision: Union[str, None] = '3f51ed896918'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faculty', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('faculty', sa.Column('short_bio', sa.Text(), nullable=True))
    op.add_column('faculty', sa.Column('recent_publications', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('faculty', sa.Column('awards', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('faculty', sa.Column('office_hours', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('faculty', 'office_hours')
    op.drop_column('faculty', 'awards')
    op.drop_column('faculty', 'recent_publications')
    op.drop_column('faculty', 'short_bio')
    op.drop_column('faculty', 'rating')
    # ### end Alembic commands ###
