"""Update Faculty model fields

Revision ID: a194144dbdf0
Revises: b5186a9c71e3
Create Date: 2025-07-06 22:26:40.131046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from database import Base


# revision identifiers, used by Alembic.
revision: str = 'a194144dbdf0'
down_revision: Union[str, None] = 'b5186a9c71e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('faculty_email_key', 'faculty', type_='unique')
    op.create_foreign_key(None, 'faculty', 'users', ['id'], ['id'])
    op.drop_column('faculty', 'name')
    op.drop_column('faculty', 'phone')
    op.drop_column('faculty', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faculty', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('faculty', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('faculty', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'faculty', type_='foreignkey')
    op.create_unique_constraint('faculty_email_key', 'faculty', ['email'])
    op.alter_column('equipment_categories', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('equipment_bookings', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('equipment', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
