"""admissions models and permissions

Revision ID: bd58d7a4eb3f
Revises: c8527c01b6bf
Create Date: 2025-07-06 10:48:04.544759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from database import Base


# revision identifiers, used by Alembic.
revision: str = 'bd58d7a4eb3f'
down_revision: Union[str, None] = 'c8527c01b6bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admission_deadlines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('requirements', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admission_deadlines_id'), 'admission_deadlines', ['id'], unique=False)
    op.create_table('admission_faqs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admission_faqs_id'), 'admission_faqs', ['id'], unique=False)
    op.create_table('admission_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('next_deadline', sa.String(), nullable=False),
    sa.Column('programs_offered', sa.Integer(), nullable=False),
    sa.Column('application_time', sa.String(), nullable=False),
    sa.Column('acceptance_rate', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admission_stats_id'), 'admission_stats', ['id'], unique=False)
    # Add MANAGE_ADMISSIONS permission and assign to OFFICER (role_id=4)
    from sqlalchemy.sql import table, column
    permissions_table = table('permissions',
        column('id', sa.Integer),
        column('name', sa.String),
        column('category', sa.String)
    )
    op.bulk_insert(permissions_table, [
        {'id': 12, 'name': 'MANAGE_ADMISSIONS', 'category': 'POST'}
    ])
    role_permissions_table = table('roles_permissions',
        column('id', sa.Integer),
        column('role_id', sa.Integer),
        column('permission_id', sa.Integer)
    )
    op.bulk_insert(role_permissions_table, [
        {'id': 100, 'role_id': 4, 'permission_id': 12}
    ])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admission_stats_id'), table_name='admission_stats')
    op.drop_table('admission_stats')
    op.drop_index(op.f('ix_admission_faqs_id'), table_name='admission_faqs')
    op.drop_table('admission_faqs')
    op.drop_index(op.f('ix_admission_deadlines_id'), table_name='admission_deadlines')
    op.drop_table('admission_deadlines')
    # ### end Alembic commands ###
